version: "3"

services:
  nginx:
    container_name: nginx
    build: requirements/nginx
    env_file: .env
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - "wordpress-volume:/var/www/wordpress"
    networks:
      - inception
    restart: on-failure

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    env_file: .env
    depends_on:
      - mariadb
    volumes:
      - "wordpress-volume:/var/www/wordpress"
    networks:
      - inception
    restart: on-failure
    expose:
     - "9000"
  
  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    env_file: .env
    volumes:
      - "mariadb-volume:/var/lib/mysql"
    networks:
      - inception
    restart: on-failure
    expose:
     - "3306"

networks:
  inception:
    driver: bridge

volumes:
  wordpress-volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/vazra/data/wordpress'
  mariadb-volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/vazra/data/mariadb'
