services:
 mariadb:
  image: mariadb:latest
  ports:
   - '3306:3306'
  volumes:
   - ./requirements/mariadb:/var/lib/mysql
  environment:
   - MYSQL_ROOT_PASSWORD=mdp123
  restart: always

 wordpress:
  image: wordpress:4.7.1-php7.0-fpm
  ports:
   - '9000:9000'
  volumes:
   - ./requirements/wordpress:/var/www/html
  environment:
   - WORDPRESS_DB_NAME=wpdb
   - WORDPRESS_TABLE_PREFIX=wp_
   - WORDPRESS_DB_HOST=mariadb
   - WORDPRESS_DB_PASSWORD=mdp123
  links:
   - mariadb
  restart: always

 nginx:
  image: nginx:latest
  ports:
    - '80:80'
  volumes:
   - ./requirements/nginx:/etc/nginx/conf.d
   - ./requirements/logs/nginx:/var/log/nginx
   - ./requirements/wordpress:/var/www/html
  links:
   - wordpress
  restart: always
