version: "3.9"

services:
	mariadb:
		container_name: mariadb
		build: ./requirements/mariadb

	wordpress:
		container_name: wordpress
		build: ./requirements/wordpress
		depends_on:
			- mariadb

	nginx:
		container_name: nginx
		build: ./requirements/nginx
		ports:
			- "443:443"
		depends_on:
			- wordpress
