CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'vazra'@'%' IDENTIFIED BY '1002';
GRANT ALL PRIVILEGES ON wordpress.* TO 'vazra'@'%';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'root1002';
